[package]
name = "lunar_macro"
version = "0.1.0"
edition = "2024"


[lib]
proc-macro = true

[dependencies]
syn = { workspace = true, features = ["full", "extra-traits"] }
quote = { workspace = true }
proc-macro2 = { workspace = true }
paste = { workspace = true }
either = { workspace = true }
heck = { workspace = true }
