[workspace]
members = ["lunar", "lunar_macro"]
resolver = "3"


[workspace.dependencies]
godot = "0.4.0"
syn = "2.0.106"
quote = "1.0.40"
proc-macro2 = "1.0.101"
paste = "1.0.15"
parking_lot = "0.12.4"
either = "1.15.0"
heck = "0.5.0"
replace_with = "0.1.8"
slotmap = "1.0.7"
ahash = "0.8.12"
